// Copyright 2019 The Samply Development Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// CodeSystem is documented here http://hl7.org/fhir/StructureDefinition/CodeSystem
type CodeSystem struct {
	Id                *string                     `json:"id,omitempty"`
	Meta              *Meta                       `json:"meta,omitempty"`
	ImplicitRules     *string                     `json:"implicitRules,omitempty"`
	Language          *string                     `json:"language,omitempty"`
	Text              *Narrative                  `json:"text,omitempty"`
	Extension         []Extension                 `json:"extension,omitempty"`
	ModifierExtension []Extension                 `json:"modifierExtension,omitempty"`
	Url               *string                     `json:"url,omitempty"`
	Identifier        []Identifier                `json:"identifier,omitempty"`
	Version           *string                     `json:"version,omitempty"`
	Name              *string                     `json:"name,omitempty"`
	Title             *string                     `json:"title,omitempty"`
	Status            PublicationStatus           `json:"status"`
	Experimental      *bool                       `json:"experimental,omitempty"`
	Date              *string                     `json:"date,omitempty"`
	Publisher         *string                     `json:"publisher,omitempty"`
	Contact           []ContactDetail             `json:"contact,omitempty"`
	Description       *string                     `json:"description,omitempty"`
	UseContext        []UsageContext              `json:"useContext,omitempty"`
	Jurisdiction      []CodeableConcept           `json:"jurisdiction,omitempty"`
	Purpose           *string                     `json:"purpose,omitempty"`
	Copyright         *string                     `json:"copyright,omitempty"`
	CaseSensitive     *bool                       `json:"caseSensitive,omitempty"`
	ValueSet          *string                     `json:"valueSet,omitempty"`
	HierarchyMeaning  *CodeSystemHierarchyMeaning `json:"hierarchyMeaning,omitempty"`
	Compositional     *bool                       `json:"compositional,omitempty"`
	VersionNeeded     *bool                       `json:"versionNeeded,omitempty"`
	Content           CodeSystemContentMode       `json:"content"`
	Supplements       *string                     `json:"supplements,omitempty"`
	Count             *int                        `json:"count,omitempty"`
	Filter            []CodeSystemFilter          `json:"filter,omitempty"`
	Property          []CodeSystemProperty        `json:"property,omitempty"`
	Concept           []CodeSystemConcept         `json:"concept,omitempty"`
}
type CodeSystemFilter struct {
	Id                *string          `json:"id,omitempty"`
	Extension         []Extension      `json:"extension,omitempty"`
	ModifierExtension []Extension      `json:"modifierExtension,omitempty"`
	Code              string           `json:"code"`
	Description       *string          `json:"description,omitempty"`
	Operator          []FilterOperator `json:"operator"`
	Value             string           `json:"value"`
}
type CodeSystemProperty struct {
	Id                *string      `json:"id,omitempty"`
	Extension         []Extension  `json:"extension,omitempty"`
	ModifierExtension []Extension  `json:"modifierExtension,omitempty"`
	Code              string       `json:"code"`
	Uri               *string      `json:"uri,omitempty"`
	Description       *string      `json:"description,omitempty"`
	Type              PropertyType `json:"type"`
}
type CodeSystemConcept struct {
	Id                *string                        `json:"id,omitempty"`
	Extension         []Extension                    `json:"extension,omitempty"`
	ModifierExtension []Extension                    `json:"modifierExtension,omitempty"`
	Code              string                         `json:"code"`
	Display           *string                        `json:"display,omitempty"`
	Definition        *string                        `json:"definition,omitempty"`
	Designation       []CodeSystemConceptDesignation `json:"designation,omitempty"`
	Property          []CodeSystemConceptProperty    `json:"property,omitempty"`
	Concept           []CodeSystemConcept            `json:"concept,omitempty"`
}
type CodeSystemConceptDesignation struct {
	Id                *string     `json:"id,omitempty"`
	Extension         []Extension `json:"extension,omitempty"`
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	Language          *string     `json:"language,omitempty"`
	Use               *Coding     `json:"use,omitempty"`
	Value             string      `json:"value"`
}
type CodeSystemConceptProperty struct {
	Id                *string     `json:"id,omitempty"`
	Extension         []Extension `json:"extension,omitempty"`
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	Code              string      `json:"code"`
}
type OtherCodeSystem CodeSystem

// MarshalJSON marshals the given CodeSystem as JSON into a byte slice
func (r CodeSystem) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherCodeSystem
		ResourceType string `json:"resourceType"`
	}{
		OtherCodeSystem: OtherCodeSystem(r),
		ResourceType:    "CodeSystem",
	})
}

// UnmarshalCodeSystem unmarshals a CodeSystem.
func UnmarshalCodeSystem(b []byte) (CodeSystem, error) {
	var codeSystem CodeSystem
	if err := json.Unmarshal(b, &codeSystem); err != nil {
		return codeSystem, err
	}
	return codeSystem, nil
}
