// Copyright 2019 The Samply Development Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

import (
	"encoding/json"
	"fmt"
	"strings"
)

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// GroupMeasure is documented here http://hl7.org/fhir/ValueSet/group-measure
type GroupMeasure int

const (
	GroupMeasureMean GroupMeasure = iota
	GroupMeasureMedian
	GroupMeasureMeanOfMean
	GroupMeasureMeanOfMedian
	GroupMeasureMedianOfMean
	GroupMeasureMedianOfMedian
)

func (code GroupMeasure) MarshalJSON() ([]byte, error) {
	return json.Marshal(code.Code())
}
func (code *GroupMeasure) UnmarshalJSON(json []byte) error {
	s := strings.Trim(string(json), "\"")
	switch s {
	case "mean":
		*code = GroupMeasureMean
	case "median":
		*code = GroupMeasureMedian
	case "mean-of-mean":
		*code = GroupMeasureMeanOfMean
	case "mean-of-median":
		*code = GroupMeasureMeanOfMedian
	case "median-of-mean":
		*code = GroupMeasureMedianOfMean
	case "median-of-median":
		*code = GroupMeasureMedianOfMedian
	default:
		return fmt.Errorf("unknown GroupMeasure code `%s`", s)
	}
	return nil
}
func (code GroupMeasure) String() string {
	return code.Code()
}
func (code GroupMeasure) Code() string {
	switch code {
	case GroupMeasureMean:
		return "mean"
	case GroupMeasureMedian:
		return "median"
	case GroupMeasureMeanOfMean:
		return "mean-of-mean"
	case GroupMeasureMeanOfMedian:
		return "mean-of-median"
	case GroupMeasureMedianOfMean:
		return "median-of-mean"
	case GroupMeasureMedianOfMedian:
		return "median-of-median"
	}
	return "<unknown>"
}
func (code GroupMeasure) Display() string {
	switch code {
	case GroupMeasureMean:
		return "Mean"
	case GroupMeasureMedian:
		return "Median"
	case GroupMeasureMeanOfMean:
		return "Mean of Study Means"
	case GroupMeasureMeanOfMedian:
		return "Mean of Study Medins"
	case GroupMeasureMedianOfMean:
		return "Median of Study Means"
	case GroupMeasureMedianOfMedian:
		return "Median of Study Medians"
	}
	return "<unknown>"
}
func (code GroupMeasure) Definition() string {
	switch code {
	case GroupMeasureMean:
		return "Aggregated using Mean of participant values."
	case GroupMeasureMedian:
		return "Aggregated using Median of participant values."
	case GroupMeasureMeanOfMean:
		return "Aggregated using Mean of study mean values."
	case GroupMeasureMeanOfMedian:
		return "Aggregated using Mean of study median values."
	case GroupMeasureMedianOfMean:
		return "Aggregated using Median of study mean values."
	case GroupMeasureMedianOfMedian:
		return "Aggregated using Median of study median values."
	}
	return "<unknown>"
}
