// Copyright 2019 - 2021 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// Identifier is documented here http://hl7.org/fhir/StructureDefinition/Identifier
type Identifier struct {
	Id        *string          `bson:"id,omitempty" json:"id,omitempty"`
	Extension []Extension      `bson:"extension,omitempty" json:"extension,omitempty"`
	Use       *IdentifierUse   `bson:"use,omitempty" json:"use,omitempty"`
	Type      *CodeableConcept `bson:"type,omitempty" json:"type,omitempty"`
	System    *string          `bson:"system,omitempty" json:"system,omitempty"`
	Value     *string          `bson:"value,omitempty" json:"value,omitempty"`
	Period    *Period          `bson:"period,omitempty" json:"period,omitempty"`
	Assigner  *Reference       `bson:"assigner,omitempty" json:"assigner,omitempty"`
}
