// Copyright 2019 The Samply Development Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// ParameterDefinition is documented here http://hl7.org/fhir/StructureDefinition/ParameterDefinition
type ParameterDefinition struct {
	Id            *string               `json:"id,omitempty"`
	Extension     []Extension           `json:"extension,omitempty"`
	Name          *string               `json:"name,omitempty"`
	Use           OperationParameterUse `json:"use"`
	Min           *int                  `json:"min,omitempty"`
	Max           *string               `json:"max,omitempty"`
	Documentation *string               `json:"documentation,omitempty"`
	Type          string                `json:"type"`
	Profile       *string               `json:"profile,omitempty"`
}
